import { createGraphQuery } from '@statewavedev/guide-graph';
import raw from '../../.statewave-guide/application.json';

/**
 * Derived from the traversal entry point rather than imported by name, so the
 * demo cannot drift from whatever shape the indexer actually produces.
 */
type ApplicationGraph = Parameters<typeof createGraphQuery>[0];
export type GraphQuery = ReturnType<typeof createGraphQuery>;
export type ApplicationNode = NonNullable<ReturnType<GraphQuery['getNode']>>;
export type FeaturePath = ReturnType<GraphQuery['resolveFeaturePath']>;
export type PathStep = FeaturePath['path'][number];
export type Evidence = PathStep['evidence'][number];

/**
 * The Product Model this demo was built from.
 *
 * Generated by `pnpm index:example` and committed, so the Inspector works
 * immediately after a clone. The output is byte-identical between runs over
 * unchanged source, which is what makes committing it reasonable — a diff shows
 * a real change in the product, not churn.
 *
 * The cast is honest about what it is: the JSON was produced by this repository's
 * own indexer against this repository's own schema, so it is not untrusted input.
 */
export const applicationGraph = raw as unknown as ApplicationGraph;

/** Traversal over the graph. Built once. */
export const graphQuery = createGraphQuery(applicationGraph);
